accounts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^login/$', auth_views.login, name="login"),
	url(r'^logout/$', auth_views.logout, name="logout"),
	url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),
]

consumer/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.dashboard, name="dashboard"),
    #url(r'^editor/$', views.editor, name="editor"),
    url(r'^loadgroups/$', views.loadgroups, name="groups"),
    url(r'^urltestfire/$', views.urltestfire, name="urltestfire"),
    url(r'^loaddata/$', views.loaddata, name="loaddata"),
    url(r'^getdata/$', views.getdata, name="getdata"),
    url(r'^gettestdata/$', views.gettestdata, name="gettestdata"),
    url(r'^ctest/$', views.ctest, name="ctest"),
    url(r'^proto1/$', views.proto1, name="proto1"),
]

navibar/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^$', views.navibar, name="navibar"),
]

supplystore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gateway.urls', namespace="gateway") ),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^consumer/', include('consumer.urls', namespace="consumer")),
    url(r'^navibar/', include('navibar.urls', namespace="navibar") ),
    url(r'^twitterapi/', include('twitterapi.urls', namespace="twitterapi") ),
    url(r'^choosem/', include('choosemodule.urls', namespace="choosemodule") ),
    url(r'^toolbox/', include('toolbox.urls', namespace="toolbox") ),
    url(r'^dropbox/', include('dropbox.urls', namespace="dropbox") ),
    url(r'^filemanager/', include('filemanager.urls', namespace="filemanager") ),
]

navibar/models.py
from django.db import models

# Create your models here.

navibar/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.core import serializers

# Create your views here.
@login_required
def navibar(request):
    return render(request, 'navibar/base.html')
    #return HttpResponse('hello')

navibar/templates/navibar/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Strand</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href=" {% static "navibar/css/main.css" %}"/>
    <!--<script src=" {% static "oiv/javascripts/modules.js" %}"></script> -->


</head>
<body>

  <!--<div id="dragger"></div> -->

  <div id="full-view">

      <div id="header">

          {% if request.user.is_authenticated %}
          <div class="menu">
            <ul>
              <li {% if section == "navbardev" %}class="selected"{% endif %}>
                 <a href="{% url "consumer:dashboard" %}">dashboard</a>
              </li>
              <li {% if section == "proto1" %}class="selected"{% endif %}>
                 <a href="{% url "consumer:proto1" %}">dashboard</a>
              </li>
              <li {% if section == "navbardev" %}class="selected"{% endif %}>
                 <a href="{% url "navibar:navibar" %}">dashboard</a>
              </li>
          </ul>
        </div>
          {% endif %}

           <div class="user">

             <a href="{% url "accounts:logout" %}">cart</a>
            {% if request.user.is_authenticated %}
              Hello {{ request.user.username }},
              <a href="{% url "accounts:logout" %}">Logout</a>
              {% else %}
              <a href="{% url "accounts:login" %}">Log-in</a>
            {% endif %}
          </div>

      </div>
      <div id="cell1"></div>

     </div>

     {% block content %}
     {% endblock %}

  <script type="text/javascript">
  </script>

</body>
</html>

navibar/templates/navibar/navbardev.html
{% extends "navibar/base.html" %}
{% block title %}navbardev{% endblock %}


{% block content %}
{% load static %}


<div class="container">
  <p>Navbardev page</p>
</div>

{% endblock %}